require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Admin::CommissionTypesController, type: :controller do

  before :each do
    login_admin
  end

  # This should return the minimal set of attributes required to create a valid
  # CommissionType. As you add validations to CommissionType, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { name: "Discounted", label: "Discounted Offers available", icon: "money" }
  }

  let(:invalid_attributes) {
     { name: "", label: "Discounted Offers available", icon: "money" }
   }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CommissionTypesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all commission_types as @commission_types" do
      commission_type = CommissionType.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:commission_types)).to eq([commission_type])
    end
  end

  describe "GET #show" do
    it "assigns the requested commission_type as @commission_type" do
      commission_type = CommissionType.create! valid_attributes
      get :show, {:id => commission_type.to_param}, valid_session
      expect(assigns(:commission_type)).to eq(commission_type)
    end
  end

  describe "GET #new" do
    it "assigns a new commission_type as @commission_type" do
      get :new, {}, valid_session
      expect(assigns(:commission_type)).to be_a_new(CommissionType)
    end
  end

  describe "GET #edit" do
    it "assigns the requested commission_type as @commission_type" do
      commission_type = CommissionType.create! valid_attributes
      get :edit, {:id => commission_type.to_param}, valid_session
      expect(assigns(:commission_type)).to eq(commission_type)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new CommissionType" do
        expect {
          post :create, {:commission_type => valid_attributes}, valid_session
        }.to change(CommissionType, :count).by(1)
      end

      it "assigns a newly created commission_type as @commission_type" do
        post :create, {:commission_type => valid_attributes}, valid_session
        expect(assigns(:commission_type)).to be_a(CommissionType)
        expect(assigns(:commission_type)).to be_persisted
      end

      it "redirects to the created commission_type" do
        post :create, {:commission_type => valid_attributes}, valid_session
        expect(response).to redirect_to(admin_commission_types_path)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved commission_type as @commission_type" do
        post :create, {:commission_type => invalid_attributes}, valid_session
        expect(assigns(:commission_type)).to be_a_new(CommissionType)
      end

      it "re-renders the 'new' template" do
        post :create, {:commission_type => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        { name: "Referrals", label: "Earn when you refer this product", icon: "money" }
      }

      it "updates the requested commission_type" do
        commission_type = CommissionType.create! valid_attributes
        put :update, {:id => commission_type.to_param, :commission_type => new_attributes}, valid_session
        commission_type.reload
        expect(commission_type.name).to eq("Referrals")
      end

      it "assigns the requested commission_type as @commission_type" do
        commission_type = CommissionType.create! valid_attributes
        put :update, {:id => commission_type.to_param, :commission_type => valid_attributes}, valid_session
        expect(assigns(:commission_type)).to eq(commission_type)
      end

      it "redirects to the commission_type" do
        commission_type = CommissionType.create! valid_attributes
        put :update, {:id => commission_type.to_param, :commission_type => valid_attributes}, valid_session
        expect(response).to redirect_to(admin_commission_types_path)
      end
    end

    context "with invalid params" do
      it "assigns the commission_type as @commission_type" do
        commission_type = CommissionType.create! valid_attributes
        put :update, {:id => commission_type.to_param, :commission_type => invalid_attributes}, valid_session
        expect(assigns(:commission_type)).to eq(commission_type)
      end

      it "re-renders the 'edit' template" do
        commission_type = CommissionType.create! valid_attributes
        put :update, {:id => commission_type.to_param, :commission_type => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested commission_type" do
      commission_type = CommissionType.create! valid_attributes
      expect {
        delete :destroy, {:id => commission_type.to_param}, valid_session
      }.to change(CommissionType, :count).by(-1)
    end

    it "redirects to the commission_types list" do
      commission_type = CommissionType.create! valid_attributes
      delete :destroy, {:id => commission_type.to_param}, valid_session
      expect(response).to redirect_to(admin_commission_types_url)
    end
  end

end
